name: saudeemmaos
description: "Global Solutions - Saude em maos"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  mask_text_input_formatter: ^2.6.0
  flutter_lints: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.11

flutter_native_splash:
  color: "#616462"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app/icon-android.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PTSans
      fonts:
         - asset: assets/fonts/PT_Sans/PTSans-Bold.ttf
           weight: 700
         - asset: assets/fonts/PT_Sans/PTSans-Regular.ttf
           weight: 400
         - asset: assets/fonts/PT_Sans/PTSans-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/PT_Sans/PTSans-Italic.ttf
           weight: 400
           style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
